import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  artifactNames,
  parseArgs,
  renderReleaseNotes,
} from "../scripts/release-notes.mjs";

test("artifactNames lists release zips and checksums", async (t) => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "codex-bar-release-notes-"));
  t.after(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  await writeFile(path.join(dir, "codex-bar-v0.1.0-macos-arm64.zip.sha256"), "checksum");
  await writeFile(path.join(dir, "codex-bar-v0.1.0-macos-arm64.zip"), "zip");
  await writeFile(path.join(dir, "ignored.txt"), "ignore");

  assert.deepEqual(await artifactNames(dir), [
    "codex-bar-v0.1.0-macos-arm64.zip",
    "codex-bar-v0.1.0-macos-arm64.zip.sha256",
  ]);
});

test("renderReleaseNotes includes install, verification, signing, and privacy details", () => {
  const notes = renderReleaseNotes({
    tag: "v0.1.0",
    artifacts: [
      "codex-bar-v0.1.0-macos-arm64.zip",
      "codex-bar-v0.1.0-macos-arm64.zip.sha256",
    ],
  });

  assert.match(notes, /^# Codex Bar v0\.1\.0/m);
  assert.match(notes, /codex plugin marketplace add Cjbuilds\/Codex-bar/);
  assert.match(notes, /npm run install:local/);
  assert.match(notes, /npm run doctor -- --live/);
  assert.match(notes, /npm run audit:privacy/);
  assert.match(notes, /ad-hoc signed/);
  assert.match(notes, /not notarized yet/);
  assert.match(notes, /does not store raw transcripts/);
  assert.match(notes, /codex-bar-v0\.1\.0-macos-arm64\.zip\.sha256/);
});

test("renderReleaseNotes handles empty artifact lists", () => {
  const notes = renderReleaseNotes({ tag: "v0.1.0", artifacts: [] });

  assert.match(notes, /Release artifacts are generated by CI/);
});

test("parseArgs reads tag, dist, and output options", () => {
  const options = parseArgs([
    "--tag", "v0.1.0",
    "--dist=/tmp/dist",
    "--output", "/tmp/release-notes.md",
  ], {});

  assert.equal(options.tag, "v0.1.0");
  assert.equal(options.distDir, "/tmp/dist");
  assert.equal(options.output, "/tmp/release-notes.md");
});

test("parseArgs can read the release tag from the environment", () => {
  assert.equal(parseArgs([], { RELEASE_TAG: "v0.1.0" }).tag, "v0.1.0");
  assert.throws(() => parseArgs([], {}), /release tag is required/);
});
