import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  artifactNames,
  parseArgs,
  renderReleaseNotes,
  signingNotice,
} from "../scripts/release-notes.mjs";

test("artifactNames lists release zips and checksums", async (t) => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "codex-bar-release-notes-"));
  t.after(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  await writeFile(path.join(dir, "codex-bar-v0.1.0-macos-arm64.zip.sha256"), "checksum");
  await writeFile(path.join(dir, "codex-bar-v0.1.0-macos-arm64.zip"), "zip");
  await writeFile(path.join(dir, "ignored.txt"), "ignore");

  assert.deepEqual(await artifactNames(dir), [
    "codex-bar-v0.1.0-macos-arm64.zip",
    "codex-bar-v0.1.0-macos-arm64.zip.sha256",
  ]);
});

test("artifactNames can filter release artifacts to the current tag", async (t) => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "codex-bar-release-notes-"));
  t.after(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  await writeFile(path.join(dir, "codex-bar-v0.1.2-macos-arm64.zip"), "old");
  await writeFile(path.join(dir, "codex-bar-v0.1.5-macos-arm64.zip"), "zip");
  await writeFile(path.join(dir, "codex-bar-v0.1.5-macos-arm64.zip.sha256"), "checksum");

  assert.deepEqual(await artifactNames(dir, "v0.1.5"), [
    "codex-bar-v0.1.5-macos-arm64.zip",
    "codex-bar-v0.1.5-macos-arm64.zip.sha256",
  ]);
});

test("renderReleaseNotes includes install, verification, signing, and privacy details", () => {
  const notes = renderReleaseNotes({
    tag: "v0.1.0",
    artifacts: [
      "codex-bar-v0.1.0-macos-arm64.zip",
      "codex-bar-v0.1.0-macos-arm64.zip.sha256",
    ],
    env: {},
  });

  assert.match(notes, /^# Codex Bar v0\.1\.0/m);
  assert.match(notes, /codex plugin marketplace add Cjbuilds\/Codex-bar/);
  assert.match(notes, /npm run setup:codex/);
  assert.match(notes, /agent-friendly setup/);
  assert.match(notes, /actual live state/);
  assert.match(notes, /CPU\/RSS/);
  assert.match(notes, /public hook approval rendering/);
  assert.match(notes, /cycling HTML proof/);
  assert.match(notes, /rejects stale idle\/completed sessions/);
  assert.match(notes, /root `AGENTS\.md`/);
  assert.match(notes, /setup command, verification commands, and safety rules/);
  assert.match(notes, /npm run smoke:clean-checkout/);
  assert.match(notes, /hidden local-file assumptions/);
  assert.match(notes, /npm run verify:published/);
  assert.match(notes, /bundled collector has Codex session-index title support/);
  assert.match(notes, /npm run audit:integration-boundary/);
  assert.match(notes, /does not patch, inject into, or modify `Codex\.app`/);
  assert.match(notes, /docs\/integration-boundary\.md/);
  assert.match(notes, /documented Codex plugin, hook, app, and MCP surfaces/);
  assert.match(notes, /npm run audit:freshness/);
  assert.match(notes, /visible idle\/completed sessions are from the current local day/);
  assert.match(notes, /npm run install:local/);
  assert.match(notes, /npm run doctor -- --live/);
  assert.match(notes, /npm run smoke:live-render/);
  assert.match(notes, /npm run smoke:clean-checkout/);
  assert.match(notes, /npm run smoke:perf/);
  assert.match(notes, /npm run audit:privacy/);
  assert.match(notes, /npm run audit:freshness/);
  assert.match(notes, /npm run audit:integration-boundary/);
  assert.match(notes, /npm run smoke:snapshot/);
  assert.match(notes, /npm run smoke:visual-proof/);
  assert.match(notes, /npm run capture:menu/);
  assert.match(notes, /codex-bar-native-proof\.html/);
  assert.match(notes, /Screen Recording permission/);
  assert.match(notes, /Hook updates use Codex's thread id when available/);
  assert.match(notes, /ad-hoc signed/);
  assert.match(notes, /not notarized yet/);
  assert.match(notes, /Session labels come from Codex desktop\/session-index generated titles or generated local database titles/);
  assert.match(notes, /raw prompt-like `title`, `preview`, and `first_user_message` values are not promoted/);
  assert.match(notes, /does not store raw transcripts/);
  assert.match(notes, /codex-bar-v0\.1\.0-macos-arm64\.zip\.sha256/);
});

test("renderReleaseNotes handles empty artifact lists", () => {
  const notes = renderReleaseNotes({ tag: "v0.1.0", artifacts: [], env: {} });

  assert.match(notes, /Release artifacts are generated by CI/);
});

test("signingNotice matches release signing mode", () => {
  assert.match(signingNotice({}), /ad-hoc signed/);
  assert.match(signingNotice({
    CODEX_STATUS_BAR_SIGN_IDENTITY: "Developer ID Application: Example Corp (TEAMID1234)",
  }), /Developer ID signed/);
  assert.match(signingNotice({
    CODEX_STATUS_BAR_SIGN_IDENTITY: "Developer ID Application: Example Corp (TEAMID1234)",
    CODEX_STATUS_BAR_NOTARIZE: "1",
  }), /notarized, stapled/);
});

test("parseArgs reads tag, dist, and output options", () => {
  const options = parseArgs([
    "--tag", "v0.1.0",
    "--dist=/tmp/dist",
    "--output", "/tmp/release-notes.md",
  ], {});

  assert.equal(options.tag, "v0.1.0");
  assert.equal(options.distDir, "/tmp/dist");
  assert.equal(options.output, "/tmp/release-notes.md");
});

test("parseArgs can read the release tag from the environment", () => {
  assert.equal(parseArgs([], { RELEASE_TAG: "v0.1.0" }).tag, "v0.1.0");
  assert.throws(() => parseArgs([], {}), /release tag is required/);
});
