#!/usr/bin/env node
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

export async function artifactNames(distDir = path.join(process.cwd(), "dist")) {
  const entries = await readdir(distDir).catch(() => []);
  return entries
    .filter((entry) => entry.endsWith(".zip") || entry.endsWith(".sha256"))
    .sort();
}

function truthy(value) {
  return ["1", "true", "yes", "on"].includes(String(value || "").toLowerCase());
}

export function signingNotice(env = process.env) {
  if (truthy(env.CODEX_STATUS_BAR_NOTARIZE)) {
    return "The zip contains `Codex Bar.app` for macOS. The app is Developer ID signed, notarized, stapled, and verified by CI.";
  }
  if (env.CODEX_STATUS_BAR_SIGN_IDENTITY && env.CODEX_STATUS_BAR_SIGN_IDENTITY !== "-") {
    return "The zip contains `Codex Bar.app` for macOS. The app is Developer ID signed and verified by CI, but it is not notarized unless `CODEX_STATUS_BAR_NOTARIZE=1` was set for the release.";
  }
  return "The zip contains `Codex Bar.app` for macOS. The app is ad-hoc signed and verified by CI, but it is not notarized yet. macOS may require approval on first launch.";
}

export function renderReleaseNotes({ tag, artifacts, env = process.env }) {
  if (!tag) throw new Error("release tag is required");
  const artifactLines = artifacts.length > 0
    ? artifacts.map((artifact) => `- ${artifact}`).join("\n")
    : "- Release artifacts are generated by CI during this workflow.";
  const signing = signingNotice(env);

  return `# Codex Bar ${tag}

Native macOS menu bar dashboard for Codex session progress.

## What It Shows

- Approval-needed attention.
- Task progress such as \`2/5 tasks\`.
- Goal status such as \`goal active\` or \`goal complete\`.
- Running, completed, and today's recent Codex sessions.
- Session rows with \`Codex N · folder · session title · progress\`.
- Deep links back into Codex threads.

## Install From Codex

\`\`\`bash
codex plugin marketplace add Cjbuilds/Codex-bar
\`\`\`

Then restart Codex, open \`/plugins\`, choose the marketplace, install **Codex Bar**, and review/trust its hooks when Codex asks.

For local verification after cloning or installing:

\`\`\`bash
npm run install:local
npm run doctor -- --live
npm run audit:privacy
\`\`\`

## Artifacts

${artifactLines}

${signing}

## Privacy

Codex Bar stores a minimized local dashboard snapshot under \`~/.codex/statusbar/state.json\`. It does not store raw transcripts, model responses, command output, tool results, API keys, access tokens, cookies, or full Codex logs.
`;
}

export function parseArgs(argv = process.argv.slice(2), env = process.env) {
  const options = {
    tag: env.RELEASE_TAG || null,
    distDir: path.join(process.cwd(), "dist"),
    output: "release-notes.md",
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const [key, inlineValue] = arg.split("=", 2);
    const nextValue = () => inlineValue ?? argv[++index];
    switch (key) {
      case "--tag":
        options.tag = nextValue();
        break;
      case "--dist":
        options.distDir = path.resolve(nextValue());
        break;
      case "--output":
        options.output = path.resolve(nextValue());
        break;
      default:
        throw new Error(`unknown option ${arg}`);
    }
  }

  if (!options.tag) throw new Error("release tag is required; pass --tag v0.1.1 or set RELEASE_TAG");
  return options;
}

export async function main(argv = process.argv.slice(2), env = process.env) {
  const options = parseArgs(argv, env);
  const packageJson = JSON.parse(await readFile(path.join(process.cwd(), "package.json"), "utf8"));
  const expectedTag = `v${packageJson.version}`;
  if (options.tag !== expectedTag) {
    throw new Error(`release tag ${JSON.stringify(options.tag)} must match package version ${JSON.stringify(expectedTag)}`);
  }

  const notes = renderReleaseNotes({
    tag: options.tag,
    artifacts: await artifactNames(options.distDir),
    env,
  });
  await writeFile(options.output, notes);
  console.log(`Release notes written to ${options.output}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
