#!/usr/bin/env node
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

export async function artifactNames(distDir = path.join(process.cwd(), "dist"), tag = null) {
  const entries = await readdir(distDir).catch(() => []);
  const tagNeedle = tag ? `${tag}-` : null;
  return entries
    .filter((entry) => entry.endsWith(".zip") || entry.endsWith(".sha256"))
    .filter((entry) => !tagNeedle || entry.includes(tagNeedle))
    .sort();
}

function truthy(value) {
  return ["1", "true", "yes", "on"].includes(String(value || "").toLowerCase());
}

export function signingNotice(env = process.env) {
  if (truthy(env.CODEX_STATUS_BAR_NOTARIZE)) {
    return "The zip contains `Codex Bar.app` for macOS. The app is Developer ID signed, notarized, stapled, and verified by CI.";
  }
  if (env.CODEX_STATUS_BAR_SIGN_IDENTITY && env.CODEX_STATUS_BAR_SIGN_IDENTITY !== "-") {
    return "The zip contains `Codex Bar.app` for macOS. The app is Developer ID signed and verified by CI, but it is not notarized unless `CODEX_STATUS_BAR_NOTARIZE=1` was set for the release.";
  }
  return "The zip contains `Codex Bar.app` for macOS. The app is ad-hoc signed and verified by CI, but it is not notarized yet. macOS may require approval on first launch.";
}

export function renderReleaseNotes({ tag, artifacts, env = process.env }) {
  if (!tag) throw new Error("release tag is required");
  const artifactLines = artifacts.length > 0
    ? artifacts.map((artifact) => `- ${artifact}`).join("\n")
    : "- Release artifacts are generated by CI during this workflow.";
  const signing = signingNotice(env);

  return `# Codex Bar ${tag}

Native macOS menu bar dashboard for Codex session progress.

## What It Shows

- Approval-needed attention.
- Task progress such as \`2/5 tasks\`.
- Goal status such as \`goal active\` or \`goal complete\`.
- Running, completed, and today's recent Codex sessions.
- Session rows with \`Codex N · folder · session title · progress\`.
- Deep links back into Codex threads.

## Install From Codex

\`\`\`bash
codex plugin marketplace add Cjbuilds/Codex-bar
\`\`\`

Then restart Codex, open \`/plugins\`, choose the marketplace, install **Codex Bar**, and review/trust its hooks when Codex asks.

For agent-friendly setup after cloning or installing:

\`\`\`bash
npm run setup:codex
\`\`\`

That validates the plugin metadata and hooks, builds and launches the app, waits for the live collector, renders the actual live state through the native formatter, samples live CPU/RSS usage, exercises approval/progress/completed state, renders those states through the native formatter, verifies public hook approval rendering, writes permission-free AppKit menu snapshots plus a cycling HTML proof, audits the live state file for privacy leaks, and rejects stale idle/completed sessions from previous days.

The repository includes a root \`AGENTS.md\` so Codex agents get the same setup command, verification commands, and safety rules immediately after cloning or opening the repo.

\`npm run smoke:clean-checkout\` copies Git-visible files to a temporary checkout and runs bounded repo checks there, so the release path catches hidden local-file assumptions.

\`npm run audit:integration-boundary\` checks that Codex Bar remains a separate native menu item and does not patch, inject into, or modify \`Codex.app\`.

\`npm run audit:freshness\` checks that visible idle/completed sessions are from the current local day while active, approval-needed, running, goal, and compacting sessions remain visible.

For individual local checks:

\`\`\`bash
npm run install:local
npm run doctor -- --live
npm run smoke:live-render
npm run smoke:clean-checkout
npm run smoke:perf
npm run audit:privacy
npm run audit:freshness
npm run audit:integration-boundary
\`\`\`

For visual proof artifacts:

\`\`\`bash
npm run smoke:snapshot
npm run smoke:visual-proof
npm run capture:menu
\`\`\`

\`smoke:visual-proof\` writes permission-free AppKit PNG artifacts and \`dist/visual-proof/codex-bar-native-proof.html\`, which cycles approval, progress, and completed native snapshots. \`capture:menu\` starts the live demo and captures a real clicked menu screenshot after macOS Screen Recording permission is granted.

## Artifacts

${artifactLines}

${signing}

## Privacy

Codex Bar stores a minimized local dashboard snapshot under \`~/.codex/statusbar/state.json\`. Session labels come from Codex desktop/session-index generated titles or generated local database titles that differ from the first prompt/preview; raw prompt-like \`title\`, \`preview\`, and \`first_user_message\` values are not promoted to menu labels. It does not store raw transcripts, model responses, command output, tool results, API keys, access tokens, cookies, or full Codex logs.
`;
}

export function parseArgs(argv = process.argv.slice(2), env = process.env) {
  const options = {
    tag: env.RELEASE_TAG || null,
    distDir: path.join(process.cwd(), "dist"),
    output: "release-notes.md",
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const [key, inlineValue] = arg.split("=", 2);
    const nextValue = () => inlineValue ?? argv[++index];
    switch (key) {
      case "--tag":
        options.tag = nextValue();
        break;
      case "--dist":
        options.distDir = path.resolve(nextValue());
        break;
      case "--output":
        options.output = path.resolve(nextValue());
        break;
      default:
        throw new Error(`unknown option ${arg}`);
    }
  }

  if (!options.tag) throw new Error("release tag is required; pass --tag v0.1.5 or set RELEASE_TAG");
  return options;
}

export async function main(argv = process.argv.slice(2), env = process.env) {
  const options = parseArgs(argv, env);
  const packageJson = JSON.parse(await readFile(path.join(process.cwd(), "package.json"), "utf8"));
  const expectedTag = `v${packageJson.version}`;
  if (options.tag !== expectedTag) {
    throw new Error(`release tag ${JSON.stringify(options.tag)} must match package version ${JSON.stringify(expectedTag)}`);
  }

  const notes = renderReleaseNotes({
    tag: options.tag,
    artifacts: await artifactNames(options.distDir, options.tag),
    env,
  });
  await writeFile(options.output, notes);
  console.log(`Release notes written to ${options.output}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
